export const MIMETYPES = {
  PNG: "image/png",
  JPEG: "image/jpeg",
  JPG: "image/jpg",
  MPEG: "audio/mpeg",
  PDF: "application/pdf",
  MP4: "video/mp4",
  CSV: "text/csv",
};

export const MIMETYPE_VS_DISPLAYTEXT = {
  [MIMETYPES.PNG]: "PNG",
  [MIMETYPES.JPEG]: "JPEG",
  [MIMETYPES.JPG]: "JPEG",
  [MIMETYPES.MPEG]: "MP3",
  [MIMETYPES.PDF]: "PDF",
  [MIMETYPES.MP4]: "MP4",
  [MIMETYPES.CSV]: "CSV",
  DEFAULT: "FILE",
};

export const TYPEFILTER = {
  TYPE: "TYPE",
  PDFS: "PDFS",
  SPREADSHEETS: "SPREADSHEETS",
  IMAGES: "IMAGES",
  VIDEOS: "VIDEOS",
  AUDIOS: "AUDIOS",
  OTHERS: "OTHERS",
};

export const TYPEFILTER_VS_FILTER_DISPLAYTEXT = {
  [TYPEFILTER.TYPE]: "Type",
  [TYPEFILTER.PDFS]: "PDFs",
  [TYPEFILTER.SPREADSHEETS]: "Spreadsheets",
  [TYPEFILTER.IMAGES]: "Photos & Images",
  [TYPEFILTER.VIDEOS]: "Videos",
  [TYPEFILTER.AUDIOS]: "Audios",
  [TYPEFILTER.OTHERS]: "Others",
};

export const TYPEFILTER_VS_MIMETYPES_MAP = {
  [TYPEFILTER.TYPE]: [],
  [TYPEFILTER.PDFS]: [MIMETYPES.PDF],
  [TYPEFILTER.SPREADSHEETS]: [MIMETYPES.CSV],
  [TYPEFILTER.IMAGES]: [MIMETYPES.PNG, MIMETYPES.JPEG, MIMETYPES.JPG],
  [TYPEFILTER.VIDEOS]: [MIMETYPES.MP4],
  [TYPEFILTER.AUDIOS]: [MIMETYPES.MPEG],
  [TYPEFILTER.OTHERS]: [
    MIMETYPES.PDF,
    MIMETYPES.CSV,
    MIMETYPES.PNG,
    MIMETYPES.JPEG,
    MIMETYPES.JPG,
    MIMETYPES.MP4,
    MIMETYPES.MPEG,
  ],
};
